---
title: "Visualization"
output: github_document
date: "2026-10-01"
---

```{r setup}
library(tidyverse)
library(patchwork)
library(p8105.datasets)
data("weather_df")
```

Now we have everything we need!

Start with a scatterplot
Try some scales

```{r}
weather_df |> 
ggplot(aes(x = tmax, y = tmin, color = name)) +
  geom_point() +
  labs(
    title = "Temperature (Max vs Min)",
    x = "Max Temperature (C)",
    y = "Min Temperqture (C)",
    color = "Location",
    caption = "Data from NOAA for three weather stations"
  ) +
 scale_x_continuous(
   breaks = c(-10, 0, 15),
   labels = c("-10 C", "0", "Fifteen")
 ) +
  scale_y_continuous(
    trans = "sqrt",
    position = "right"
  )
```

Let's look at color

```{r}
weather_df |> 
  ggplot(aes(x = tmax, y = tmin, color = name)) +
  geom_point() +
  scale_color_hue(h = c(100, 300))
```

Color-blind friendly
```{r}
weather_df |> 
  ggplot(aes(x = tmax, y = tmin, color = name)) +
  geom_point() +
  viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  )
```

## Themes

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point() +
    viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  ) + 
  theme(legend.position = "bottom") +
# changes where the legend is on the graph. Could also put in on the left, the top, etc
    theme_minimal()
# theme_minimal overwrites the previous theme statement and just makes it the minimal theme
```

Update the tmax vs data plot

```{r}

  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = 0.5) +
    labs(
    x = "Date",
    y = "Max Temperature (C)",
    color = "Location",
    caption = "Data from NOAA for three weather stations"
  ) +
    viridis::scale_color_viridis(
    name = "Location",
    discrete = TRUE
  ) + 
  facet_grid(.~name)


```


```{r}

  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
  geom_smooth(se = FALSE)
    labs(
    title = "Seasonal trends in max temp",
    x = "Date",
    y = "Max Temperature (C)",
    caption = "Max daily temp in three weather stations in 2021 and 2022",
        color = "Location"
  ) +
    viridis::scale_color_viridis(
    discrete = TRUE
  ) + 
    theme_minimal() +
      theme(legend.position = "bottom")


```


## Two more weird but useful plot things

```{r}
central_park_df =
  weather_df |> 
  filter(name == "CentralPark_NY")

molokai_df = 
  weather_df |> 
  filter(name == "Molokai_HI")

ggplot(molokai_df, aes(x = date, y = tmax, color = name)) +
  geom_point() +
geom_line(data = central_park_df)
```

Multiple panels with different plot types

```{r}
ggp_tmax_tmin =
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name))+
  geom_point() +
  theme(legend.position = "none")


ggp_prcp_density =
  weather_df |> 
  filter(prcp > 0) |> 
  ggplot(aes(x = prcp, fill = name)) +
  geom_density(alpha = .5) +
    theme(legend.position = "none")

ggp_seasonal =
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point() +
    theme(legend.position = "bottom")

(ggp_tmax_tmin + ggp_prcp_density) / ggp_seasonal
# this is using patchwork package
```

## Data manipulation

Start with factors

boxplots!

```{r}

weather_df |> 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()

# defaults to putting factor variables in alphabetical order


```

```{r}
weather_df |> 
  mutate(name = fct_relevel(name, c("Molokai_HI", "CentralPark_NY", "Waterhole_WA"))) |> 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()

weather_df |> 
  mutate(name = fct_reorder(name, tmax)) |> 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
# putting name in order of median tmax
```


Make that distribution plot
```{r}
weather_df |> 
  select(name, tmax, tmin) |> 
  pivot_longer(
    tmax:tmin,
    names_to = "observation",
    values_to = "temp"
  ) |> 
  ggplot(aes(x = temp, fill = observation)) +
  geom_density(alpha = .5)+
  facet_grid(. ~ name)

```

Make an FAS plot
```{r}
pups_df =
  read_csv("data/FAS_pups.csv", skip = 3, na = c("", ".", "NA")) |> 
  janitor::clean_names()

litters_df = read_csv("data/FAS_litters.csv", na = c("", ".", "NA")) |> 
  janitor::clean_names() |> 
  separate(group, into = c("dose", "day_of_tx"), 3)

fas_df =
  left_join(pups_df, litters_df, by = "litter_number")

fas_df |> 
  select(dose, day_of_tx, starts_with("pd")) |> 
  pivot_longer(
    starts_with("pd"),
    names_to = "outcome",
    values_to = "pn_day"
  ) |> 
  drop_na() |> 
  ggplot(aes(x = dose, y = pn_day))+
  geom_boxplot() +
  facet_grid(day_of_tx ~ outcome)
```

